<?php
/**
 * @category   Ksolves
 * @package    Ksolves_LayeredNavigation
 * @author     Ksolves Team
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Ksolves\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
 <!-- create object of helper class -->
<?php $helper = $this->helper('Ksolves\LayeredNavigation\Helper\Data'); ?>

<?php if($filter instanceof Magento\CatalogSearch\Model\Layer\Filter\Price ): ?>
    <?php if ($helper->getPriceSlider()) : ?>
        <?php $getPriceFilterValue  = $block->getRequest()->getParam($filter->getRequestVar()); ?>
        <?php $ksPriceRange         =  $this->getCategoryProductsPriceRange($filter);?>
        <?php $ksPriceUrl           = $this->getProductsFilterUrl($filter); ?>
        <?php list($kspriceFrom, $kspriceTo) = $getPriceFilterValue ? explode('-', $getPriceFilterValue) : [$ksPriceRange['min'], $ksPriceRange['max']]; ?>
        <script>
            var ksPriceUrl = "<?=$ksPriceUrl;?>";
            var ksCurrencySymbol = "<?= $block->getCurrentCurrencySymbol();?>";
            require([
                'jquery',
                'priceUtils',
                "jquery/ui",
                'domReady!'
            ], function($,utils){
                /* price slider */
                $( "#ks-price-slider" ).slider({
                    range: true,
                    min: <?=$ksPriceRange['min']?> ,
                    max: <?=$ksPriceRange['max']?>,
                    values: [ <?= $kspriceFrom ?>, <?= $kspriceTo?> ],
                    slide: function( event, ui ) {
                        $( "#amount" ).val( ksCurrencySymbol + ui.values[ 0 ] + " - " + ksCurrencySymbol + ui.values[ 1 ] );
                    },
                    change: function( event, ui ) {
                        var filterUrl = ksPriceUrl.replace("price=","price="+ui.values[0]+"-"+ui.values[1]);
                        /* ajax call to get products */
                        $.ajax({
                            url: filterUrl,
                            type: 'POST',
                            dataType: 'json',
                            data: {},
                            showloader : true,
                            success: function(response) 
                            { 
                                /* replace url */
                                history.replaceState(null, null, filterUrl);

                                /* update layered navigation content */
                                $('.sidebar-main').html(response.sidebar_main).trigger('contentUpdated'); 
                                /* update the products*/     
                                $('.column.main').html(response.products).trigger('contentUpdated'); 
                            },
                            error: function (xhr, status, errorThrown) {
                                alert('Error happens. Try again.');
                            }
                        });
                    }
                });
                /* update the amount */
                $( "#amount" ).val( ksCurrencySymbol+ <?= $kspriceFrom ?> +
                 " - "+ ksCurrencySymbol + <?= $kspriceTo ?> );
            });
        </script>
        <label for="amount">Price range:</label>
        <input type="text" id="amount" style="border:0; color:#f6931f; font-weight:bold;" readonly="true">
        <p class="ks-product-count">(<?= $block->getTotalProducts($filter);?>) products</p>
        <div id="ks-price-slider"></div>

    <?php else : ?>
        <ol class="items">
            <?php foreach ($filterItems as $filterItem): ?>
                <li class="my item">
                    <?php if ($filterItem->getCount() > 0): ?>
                        <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                            <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                            <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                                <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                                    <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                            <?php endif; ?>
                        </a>
                    <?php else:?>
                        <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                        <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                            <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                                <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                        <?php endif; ?>
                    <?php endif; ?>
                </li>
            <?php endforeach ?>
        </ol>
    <?php endif; ?>

<?php else:?>
    <ol class="items">
        <?php foreach ($filterItems as $filterItem): ?>
            <li class="my item">
                <?php if ($filterItem->getCount() > 0): ?>
                    <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                        <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                        <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                            <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                                <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                        <?php endif; ?>
                    </a>
                <?php else:?>
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                <?php endif; ?>
            </li>
        <?php endforeach ?>
    </ol>
<?php endif;?>
